import { hashRecord,clone } from './identity.js';
const WORLD='static-field/worldseed-001', DEST='foreign-room-seed-001';
const time=(m)=>`2026-09-21T13:${String(m).padStart(2,'0')}:00.000Z`;
function event(kind,id,at,payload={}){const body={kind,id,at,payload,sourceSystem:kind.startsWith('meal.')?'foreign-room-seed-001':WORLD};return {...body,hash:hashRecord('origin-local-event-v01',body)};}
export function createFirstCrossingFixture(){
 const source={worldId:WORLD,constitutionRef:'static-field:WORLDSEED-001',inputProvenance:{kind:'synthetic-specimen',donorBranch:'feat/static-field-first-bell-001',donorCommit:'59d6adff7cc48de57340dc5c924bd26646105d41'},firstBellPlayReceipt:{receiptId:'fixture:static-field/first-bell-play-001',receiptType:'FirstBellPlayReceipt',sourceStatus:'unresolved',secretNoticed:true,relationTraced:true},bell:{sourceStatus:'unresolved',count:2},knock:{sourceStatus:'unresolved',interpretation:null},gateRelationTraced:true,chairs:['chair-a'],localCharge:2,localEvents:[event('PORCH_ARRIVAL','sf-001',time(0)),event('OBJECT_PREPARED','sf-002',time(1),{objectId:'chair-a'}),event('BELL_OCCURRENCE','sf-003',time(2),{ordinal:1,sourceStatus:'unresolved'}),event('BELL_OCCURRENCE','sf-004',time(3),{ordinal:2,sourceStatus:'unresolved'}),event('RESONANCE_RELATION_TRACED','sf-005',time(4),{promotedClaim:false}),event('KNOCK_OCCURRENCE','sf-006',time(5),{sourceStatus:'unresolved'}),event('FIRST_BELL_PLAY_CLOSED','sf-007',time(6),{bellSourceStatus:'unresolved'})]};
 const destination={worldId:DEST,constitutionRef:'foreign-room-seed-001/fictional-local-law',localClock:time(9),meal:{status:'half-finished',startedAt:time(0)},localEvents:[event('meal.started','fr-001',time(0)),event('meal.half-finished','fr-002',time(8))]};
 const party={partyId:'fixture:party-1',anchorRef:'card:first-inheritance',currentWorldRef:WORLD,members:[{kind:'human',participantRef:'fixture:human-1'}],openThreadRefs:['thread:bell-unresolved'],carriedCardRefs:['card:first-inheritance'],priorCrossingRefs:[]};
 const gate={gateId:'SCREEN-DOOR-001',sourceGateRef:'fixture:derived-static-field-gate',sourceWorldRef:WORLD,sourceLocationRef:'static-field/worldseed-001/the-porch',destinationWorldRef:null,status:'LATENT',authorized:false,evidenceRefs:['sf-005'],unresolvedConditions:['destination','opening-authority','transfer-policy']};
 const inputProvenance={kind:'synthetic-specimen',sourceReceiptRef:source.firstBellPlayReceipt.receiptId,donorBranch:source.inputProvenance.donorBranch,donorCommit:source.inputProvenance.donorCommit,nonClaims:['not_a_live_static_field_receipt','does_not_resolve_bell_cause']};
 return clone({source,destination,party,gate,inputProvenance});
}
